export const ALGOLIA_APP_ID = process.env.ALGOLIASEARCH_APPLICATION_ID;
export const ALGOLIA_API_KEY = process.env.ALGOLIASEARCH_API_KEY;
export const ALGOLIA_RECIPE_INDEX_NAME = process.env.ALGOLIASEARCH_RECIPE_INDEX_NAME;
